FROM quay.io/pypa/manylinux_2_28_x86_64
COPY entrypoint.sh /entrypoint.sh
# We need ninja >= 1.10
RUN yum -y install https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/n/ninja-build-1.10.2-3.el7.x86_64.rpm
ENTRYPOINT ["/entrypoint.sh"]
